train: true

model:
  name: /home/tmittra/models/Qwen2.5-1.5B-Instruct

output:
  dir: ./lora_output

training:
  num_train_epochs: 32
  per_device_train_batch_size: 4

inference:
  use_adapter: true
  adapter_dir: ./lora_output/adapter